### ISSUE TITLE
Add root filter path option

### ISSUE THREAD

**Issue by rogerfar** [shawnxusy/babel-plugin-react-generate-property#6]
Hey @shawnxusy thanks for this useful library!

Our library has various depths of paths, for example you have:
`src/App.tsx`
or
`src/libs/mylib/components/component1/Component1.tsx`

Problem with the `dirLevel` path is that it strips the directory, so you get:
`src_app` for `src/App.tsx`
and
`component1_component1` for `src/libs/mylib/components/component1/Component1.tsx`

When you nest components deeper in  your file hierarchy you start missing some information.

Would it be an idea to add an option something like `stripDirs` which takes off the first x amount of directories?

**Comment by shawnxusy** [comment]
Hi @rogerfar just making sure I understand the ask here:
Say for `src/libs/mylib/components/component1/Component1.tsx`, and given `stripDirs` value of `2`, it would yield 
`mylib_components_component1_Component1`, is that correct?

**Comment by rogerfar** [comment]
Correct, a more practical example would be:

`/usr/hpme/user/projects/react-app/App.tsx` with a stripDirs value of 5, would yield `react_app_app`.
