### ISSUE TITLE
Update npm version 1.0.5 -> 1.1.0

### ISSUE THREAD

**Issue by Oleg2tor** [shawnxusy/babel-plugin-react-generate-property#8]
Hi.
Thanks for what you doing.
Please, update npm version to the latest.
I wish to use new configs like ‘addModuleClassnames’ and ‘ignoreNodeNames’

**Comment by shawnxusy** [comment]
Sure, will do in the next few days.

**Comment by shawnxusy** [comment]
@Oleg2tor sorry, can you specify what exactly are you looking for? which package specifically to update?

**Comment by shawnxusy** [comment]
The package's npm version is already at 1.10

**Comment by Oleg2tor** [comment]
@shawnxusy  I men't here https://www.npmjs.com/package/babel-plugin-react-generate-property
Latest version is 1.0.5

**Comment by shawnxusy** [comment]
got it, just updated the lib and published `1.1.2` to npm registry.

**Comment by shawnxusy** [comment]
let me know if you run into issues, thanks for the feedback!

**Comment by Oleg2tor** [comment]
@shawnxusy Thank you very much!
